2016-07-31 01:34:40.465 +10:00 [Information] Application startup complete!
2016-07-31 01:34:40.483 +10:00 [Fatal] This is a critical message
2016-07-31 01:34:40.493 +10:00 [Warning] This is a warning message
2016-07-31 01:34:40.494 +10:00 [Error] This is an error message
2016-07-31 01:34:40.972 +10:00 [Information] Request starting HTTP/1.1 GET http://localhost:8081/  
2016-07-31 01:34:41.126 +10:00 [Information] Request finished in 167.0068ms 200 
2016-07-31 01:40:14.051 +10:00 [Information] Application startup complete!
2016-07-31 01:40:14.073 +10:00 [Fatal] This is a critical message
2016-07-31 01:40:14.076 +10:00 [Warning] This is a warning message
2016-07-31 01:40:14.076 +10:00 [Error] This is an error message
2016-07-31 01:40:14.684 +10:00 [Information] Request starting HTTP/1.1 GET http://localhost:8081/  
2016-07-31 01:40:14.710 +10:00 [Error] An unhandled exception has occurred while executing the request
System.InvalidOperationException: Oops!
   at Lab4.Startup.<>c.<<Configure>b__6_1>d.MoveNext() in C:\Users\jonga\Documents\GitHub\aspnetcore-workshop\LabCode\Lab4C\src\Lab4\Startup.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
2016-07-31 01:40:15.012 +10:00 [Information] Request finished in 363.0292ms 500 text/html; charset=utf-8
2016-07-31 02:29:18.872 +10:00 [Information] Application startup complete!
2016-07-31 02:29:18.900 +10:00 [Fatal] This is a critical message
2016-07-31 02:29:18.902 +10:00 [Warning] This is a warning message
2016-07-31 02:29:18.903 +10:00 [Error] This is an error message
2016-07-31 02:29:24.112 +10:00 [Information] Request starting HTTP/1.1 GET http://localhost:8081/  
2016-07-31 02:29:24.209 +10:00 [Error] An unhandled exception has occurred while executing the request
System.InvalidOperationException: Oops!
   at Lab4.Startup.<>c.<<Configure>b__6_3>d.MoveNext() in C:\Users\jonga\Documents\GitHub\aspnetcore-workshop\LabCode\Lab4C\src\Lab4\Startup.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
2016-07-31 02:29:24.515 +10:00 [Information] Request finished in 446.5439ms 500 text/html; charset=utf-8
2016-07-31 02:30:29.604 +10:00 [Information] Application startup complete!
2016-07-31 02:30:29.638 +10:00 [Fatal] This is a critical message
2016-07-31 02:30:29.642 +10:00 [Warning] This is a warning message
2016-07-31 02:30:29.643 +10:00 [Error] This is an error message
2016-07-31 02:30:31.557 +10:00 [Information] Request starting HTTP/1.1 GET http://localhost:8081/  
2016-07-31 02:30:31.637 +10:00 [Error] An unhandled exception has occurred: Oops!
System.InvalidOperationException: Oops!
   at Lab4.Startup.<>c.<<Configure>b__6_3>d.MoveNext() in C:\Users\jonga\Documents\GitHub\aspnetcore-workshop\LabCode\Lab4C\src\Lab4\Startup.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2016-07-31 02:30:31.879 +10:00 [Information] Request finished in 373.2943ms 500 text/html
2016-07-31 02:30:32.511 +10:00 [Information] Request starting HTTP/1.1 GET http://localhost:8081/  
2016-07-31 02:30:32.562 +10:00 [Error] An unhandled exception has occurred: Oops!
System.InvalidOperationException: Oops!
   at Lab4.Startup.<>c.<<Configure>b__6_3>d.MoveNext() in C:\Users\jonga\Documents\GitHub\aspnetcore-workshop\LabCode\Lab4C\src\Lab4\Startup.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2016-07-31 02:30:32.563 +10:00 [Information] Request finished in 52.6871ms 500 text/html
